### ISSUE TITLE
Allow changing filename generated by plugin-js

### ISSUE THREAD

**Issue by jbarreiros** [drwpow/cobalt-ui#126]
Both `plugin-css` and `plugin-sass` support passing a `filename` option to change the name of the generated file.

```js
export interface Options {
  /** output file (default: "./tokens/tokens.css") */
  filename?: string;
  ...
```

Would it be possible to add the same option to `plugin-js`?

**Comment by drwpow** [comment]
The plugin does support setting filename! It’s just done with the `js` and `json` keys individually so you can control the output of both: https://cobalt-ui.pages.dev/docs/plugins/js/

But please let me know if there’s any issue you encounter

**Comment by jbarreiros** [comment]
Oh dang 🤦🏻 totally missed that. Thank you.
