### ISSUE TITLE
bug: wrong typing for param of token function

### ISSUE THREAD

**Issue by dsvgl** [drwpow/cobalt-ui#14]
Hey,

As the title says, typings for token function (the overload for modes) is wrong. This results in Typescript doesn't error when passing non-valid token names.

![SCR-20221028-w5h](https://user-images.githubusercontent.com/97700093/198734217-4dabf173-2a4a-46d9-8e8f-de85227b52b6.png)

![SCR-20221028-vy0](https://user-images.githubusercontent.com/97700093/198734270-194ac26c-f186-45e9-b5ff-9984a9718c6a.png)

After changing to `tokens` it screams like it should :)

![SCR-20221028-w65](https://user-images.githubusercontent.com/97700093/198734392-8312f72a-6d4f-40bc-8b78-4aa4bbec9e9d.png)

Great library btw! Very promising.

**Comment by drwpow** [comment]
Awesome bug report, thank you! 🎉 The TypeScript typing is fairly new; thanks for finding a bug. Will get this patched later today.

And thank you! Would be curious to hear your thoughts on how it works for you, or what you’d like to see from it (feel free to create some discussion posts  for ideas you have)

**Comment by dsvgl** [comment]
Thx for the quick fix! Follow-up with a new bug because of this fix (😄) here: https://github.com/drwpow/cobalt-ui/issues/17

**Comment by dsvgl** [comment]
btw, I'm currently exploring Design Systems/Tokens world. Cobalt works quite well so far and I like the simplicity and also the W3C token format. I'm working on a multi-brand/whitelabel app. So I need a way to define global tokens and override some per brand. This would need some way to have multiple json files and merging them before build.
For building: it would be great to have a JS API in addition to the CLI. My plan is to build a Nuxt 3 module that decides which brand to build for and make the tokens available to all apps.

If you think those are viable feature requests, I can create issues for them.

In general, I wonder if Cobalt wants to be the next Style Dictionary, but be closer to the spec? The little I saw/experimented with Style Dictionary till now lets me to believe that most features it provides are legit and would need to be implemented here as well.

**Comment by drwpow** [comment]
Yeah that’s an interesting idea. I also maintain an OpenAPI/JSON Schema library, so the concept of orchestrating multiple JSON documents together (composition) is a concept I’m familiar with that doesn’t seem to be present in the current W3C token spec.

I can’t really commit to adding anything to this library until I see it, but I am always open to posting proposals! Outlining a detailed usecase of how a feature would work, and what problem it would solve, would be super helpful. Feel free to open issues regarding that.

And similarly to Style Dictionary. I haven’t really used Style Dictionary in a big project, but if there are any specific concepts it has that are helpful to have, I’d definitely consider adding it to Cobalt. In general, I think Cobalt (or should I say the W3C design token spec) is closer to Style Dictionary than anything else.
