### ISSUE TITLE
typescript: token function always wants `mode` as second argument

### ISSUE THREAD

**Issue by dsvgl** [drwpow/cobalt-ui#17]
After the fix here https://github.com/drwpow/cobalt-ui/issues/14 Typescript now complains about a second argument `modeName` is missing.

![SCR-20221030-az](https://user-images.githubusercontent.com/97700093/198854377-bbebf2f6-8ccc-49c8-b8b0-d5105ff7a685.png)

**Comment by drwpow** [comment]
Thanks for filing another one! You are now our top bug reporter 🏆

What version of TypeScript are you using? I am having a little trouble reproducing that locally.

**Comment by dsvgl** [comment]
I use Typescript 4.8.4

I'm not an TS expert. After some tinkering, this gives me correct typechecking and intellisense (used your apple example):

```ts
export declare function token(tokenID: keyof typeof tokens): typeof tokens[typeof tokenID];

export declare function token<T extends keyof typeof modes, K extends keyof typeof modes[T]>(
  tokenID: T,
  modeName: K,
): typeof modes[typeof tokenID];
```

![SCR-20221101-uw6](https://user-images.githubusercontent.com/97700093/199344978-59145d6e-b0d0-4568-8d33-0492ab21fa7b.png)
![SCR-20221101-uwe](https://user-images.githubusercontent.com/97700093/199344998-16b9fb1e-3929-4bfd-8f33-0130386b1934.png)
![SCR-20221101-uwy](https://user-images.githubusercontent.com/97700093/199345016-f5b4ff08-8b71-4459-b7ab-4a73eb7e68c3.png)
![SCR-20221101-uy0](https://user-images.githubusercontent.com/97700093/199345054-7774272b-cabf-49e0-84f4-3319e24e593f.png)

**Comment by drwpow** [comment]
Thank you! Will give that a try. And I’ll see if there’s a test I can write that catches this. I find typechecking tests like this a little tricky to write, but they’re worth having now.

**Comment by dsvgl** [comment]
Maybe you can look into how @mattpocock is doing type "checking" in his courses. eg here: https://github.com/total-typescript/type-transformations-workshop/blob/eaba59ce5d28c3217076c64496e39cc4f6a81b8f/src/04-conditional-types-and-infer/20-type-helpers-pattern.solution.ts#L5
By using these helpers: https://github.com/total-typescript/type-transformations-workshop/blob/main/src/helpers/type-utils.ts

**Comment by mattpocock** [comment]
https://github.com/SamVerschueren/tsd

This is also great

**Comment by drwpow** [comment]
Fixed via https://github.com/drwpow/cobalt-ui/commit/c72ea6ffff3e30ec4d21f0b556e0ea218c97180a! 🎉
