### ISSUE TITLE
Allow empty groups?

### ISSUE THREAD

**Issue by james-nash** [drwpow/cobalt-ui#206]
I've noticed that Cobalt errors when it encounters an empty group in a DTCG file. In my current setup, which uses [Tokens Brücke](https://www.figma.com/community/plugin/1254538877056388290/tokensbrucke) to export DTCG from our Figma library's variables, I end up with an empty group. (FWIW, the reason we have an empty group is because our design system is still a work in progress, and we're scaffolding out groups before adding actual tokens into them.)

I've worked around this with a simple script that removes the offending group from the DTCG file, before it gets passed into Cobalt. However, I think it would be helpful if Cobalt was more permissive and just ignored empty groups rather than throwing an error. (or else this was downgraded to a warning)

It would simplify my setup a little. But I suspect it's a situation others might also encounter, so it could help others too.

FWIW, the [DTCG spec doesn't say anything about empty groups](https://tr.designtokens.org/format/#groups), so Cobalt's approach is a valid interpretation. However, I'll raise an issue in the DTCG repo later to suggest amending the spec to be more specific about whether (or not?) empty groups are allowed.

**Comment by drwpow** [comment]
> However, I think it would be helpful if Cobalt was more permissive and just ignored empty groups rather than throwing an error. (or else this was downgraded to a warning)

Yeah I think just raising a warning and ignoring it is the right call. I think people should be aware they have empty groups in their `tokens.json`. But you’re right—it shouldn’t prevent generation IMO. I don’t think warning for groups that, say, have `$description` or `$extensions` but not tokens should generate any noise; only for truly empty groups (`{}`).

I never made an intentional decision to err on empty groups; I just really never thought to test for it. I could release a patch for this fairly quickly.

**Comment by c1rrus** [comment]
Sweet! Thanks for the quick response. If it helps, I could contribute a PR for this.

**Comment by c1rrus** [comment]
(btw, @james-nash is me too. I have separate GitHub accounts for work and personal stuff)

**Comment by drwpow** [comment]
> Sweet! Thanks for the quick response. If it helps, I could contribute a PR for this.

Would love a PR for this! Should be as simple as [changing this line in core](https://github.com/drwpow/cobalt-ui/blob/main/packages/core/src/parse/index.ts#L92). Also selfishly would love for the great James Nash’s name to be a contributor to this project 🙂 

> (btw, @james-nash is me too. I have separate GitHub accounts for work and personal stuff)

Aha! I knew it! No wonder I had never seen you both in the same room before 😉

**Comment by c1rrus** [comment]
Cool, I'll have a go at making a PR tomorrow.

> Aha! I knew it! No wonder I had never seen you both in the same room before 😉

"Never cross the streams" It's a miracle that the universe didn't implode! 🤪
