### ISSUE TITLE
Error With Custom Token Types

### ISSUE THREAD

**Issue by velin-deity** [drwpow/cobalt-ui#246]
Hello,
I noticed that since version `1.11.0` our pipeline throws an error when running the `co build` command.

From my investigation, the problem is with the new logic introduced in [packages/core/src/lint-core/rules/duplicate-values.ts](https://github.com/drwpow/cobalt-ui/commit/4b02c6bde0067950cbcb7b81163488c45bbc65c9#diff-51b0abef64c7e012735d39cc8228e3a1769a091582537196621fc83fa1ead889). 

Coming to line 55 with a type that has not been defined in the initial `values` object throws `Cannot read properties of undefined`. In reality, any token whose type returns an empty or undefined set is automatically not a duplicate.

**Comment by drwpow** [comment]
Good investigation! That’s a quick fix; will patch that right up
