### ISSUE TITLE
Nested object support in the js plugin

### ISSUE THREAD

**Issue by mike-engel** [drwpow/cobalt-ui#73]
For some cases, having a proper nested object for js tokens would be preferrable over dot-notation strings:

```js
// fine, but not optimal sometimes
{
  'colors.gray': '#123456',
  'colors.black': '#000000',
  'colors.white': '#FFFFFF',
}

// would be better in some instances
{
  colors: {
    gray: '#123456',
    black: '#000000',
    white: '#FFFFFF',
  }
}
```

Would you be open to a config option to output a nested object rather than dot-notation string accessors?

**Comment by drwpow** [comment]
Oh yes! That’s a great idea. While I still feel that a flat array is a better default, I do agree that there are times when you just want to export a flat JS object.

And the nice part is, TypeScript-wise, you don’t even need to type it! It’ll just figure itself out 😄 

But anyway, yes, would be open to adding this
