### ISSUE TITLE
Allow arrows of shadows

### ISSUE THREAD

**Issue by snicol21** [drwpow/cobalt-ui#88]
@drwpow i definitely agree with your recommendation you made here to [support multiple shadows](https://github.com/design-tokens/community-group/issues/100#issuecomment-1012516875), my specific use case is leveraging designs from Material UI, whose shadow tokens are an [array of 3 shadows](https://mui.com/material-ui/customization/default-theme/)

"0px 2px 1px -1px rgba(0,0,0,0.2),
0px 1px 1px 0px rgba(0,0,0,0.14),
0px 1px 3px 0px rgba(0,0,0,0.12)"

It sounds like you were considering expanding your tool to allow arrays, is that still the case?

**Comment by snicol21** [comment]
Which it also appears that your spec matches the community spec (as it should), but is also missing "inset" from the shadow objects as also mentioned on this same [shadow feedback](https://github.com/design-tokens/community-group/issues/100#issuecomment-1037948510)

**Comment by drwpow** [comment]
> Which it also appears that your spec matches the community spec (as it should), but is also missing "inset" from the shadow objects as also mentioned on this same [shadow feedback](https://github.com/design-tokens/community-group/issues/100#issuecomment-1037948510)

Ah that’s a good callout—this should definitely support the `inset` property. 👍 

> It sounds like you were considering expanding your tool to allow arrays, is that still the case?

Checking back on that thread, most of the authors seemed open to the idea of supporting an array of shadows, so I don’t see why not 🙂. But I think it should probably be limited to the shadow type specifically, to avoid opening a can of worms with other types (while an array of shadows has a clear application—layer them—the case is not so with many other types)
