### ISSUE TITLE
Modes can't begin with numbers

### ISSUE THREAD

**Issue by snicol21** [drwpow/cobalt-ui#91]
I created a "fontSize" `dimension` with a variety of modes, but I was surprised to find out that mode names can't be prefixed with numbers

![Screenshot 2023-08-28 at 5 15 08 PM](https://github.com/drwpow/cobalt-ui/assets/15724638/05c0496f-2070-43d6-a976-c78570f48877)

Is this expected? Or is this a bug?

**Comment by drwpow** [comment]
Oh no that’s just JavaScript: you have to surround the keys with quotes. Identifiers can’t start with a number character (but they can have a number character elsewhere in the identifier).

But let me know if when generating code if there’s an error.

**Comment by drwpow** [comment]
Oh I see this is a bug with generation. Will post a fix to this (sorry didn’t mean to close)

**Comment by drwpow** [comment]
Fixed! Published new versions of everything. But bumping `@cobalt-ui/plugin-js` specifically should fix your issue
